apiVersion: '2021-10-01'
location: southeastasia
name: multi-container-aci
properties:
  containers:
  - name: client
    properties:
      image: udemydemoregistry.azurecr.io/multi-client:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 0.5
  - name: nginx
    properties:
      image: udemydemoregistry.azurecr.io/multi-nginx:latest
      ports:
      - port: 80
        protocol: TCP
      resources:
        requests:
          cpu: 0.2
          memoryInGB: 0.2
  - name: server
    properties:
      image: udemydemoregistry.azurecr.io/multi-server:latest
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
  - name: worker
    properties:
      image: udemydemoregistry.azurecr.io/multi-worker:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 0.5
  - name: redis-server
    properties:
      image: udemydemoregistry.azurecr.io/redis:alpine
      resources:
        requests:
          cpu: 0.8
          memoryInGB: 1.3
  - name: postgres-database
    properties:
      image: udemydemoregistry.azurecr.io/postgres:alpine
      environmentVariables:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_DB
        value: "postgres"
      secureEnvironmentVariables:
      - name: POSTGRES_PASSWORD
        value: PGPassword
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 2.0
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: TCP
      port: 80
    dnsNameLabel: multi-container-aci
  imageRegistryCredentials:
  - server: ACRLoginServer
    username: ACRUsername
    password: ACRPassword
type: Microsoft.ContainerInstance/containerGroups