name: Build, Push, and Deploy Multi-Container App
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

env:
  RESOURCE_GROUP: "TestUdemyCourseRG"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Client Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/multi-client ./client
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/multi-client:latest

      - name: Build and Push Nginx Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/multi-nginx ./nginx
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/multi-nginx:latest

      - name: Build and Push Server Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/multi-server ./server
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/multi-server:latest

      - name: Build and Push Worker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/multi-worker ./worker
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/multi-worker:latest

      - name: Pull and Push Redis Image
        run: |
          docker pull redis:alpine
          docker tag redis:alpine ${{ secrets.ACR_LOGIN_SERVER }}/redis:alpine
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/redis:alpine

      - name: Import Redis & Postgres from Docker Hub to ACR
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az acr import \
              --name ${{ secrets.ACR_LOGIN_SERVER }} \
              --source docker.io/library/postgres:15-alpine \
              --image postgres:15-alpine \
              --force

            az acr import \
              --name ${{ secrets.ACR_LOGIN_SERVER }} \
              --source docker.io/library/redis:7.2-alpine \
              --image redis:7.2-alpine \
              --force

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Inject Secrets into YAML
        run: |
          sed -i "s|ACRLoginServer|${{ secrets.ACR_LOGIN_SERVER }}|g" ./aci-compose.yaml
          sed -i "s|ACRUsername|${{ secrets.ACR_USERNAME }}|g" ./aci-compose.yaml
          sed -i "s|ACRPassword|${{ secrets.ACR_PASSWORD }}|g" ./aci-compose.yaml
          sed -i "s|PGPassword|${{ secrets.PG_PASSWORD }}|g" ./aci-compose.yaml

      - name: Deploy Multi-Container to ACI
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az container create \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --file ./aci-compose.yaml \
              --no-wait