name: Build, Push, and Deploy Multi-Container App
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

env:
  RESOURCE_GROUP: "TestUdemyCourseRG"
#  ACI_NAME: "multi-container-aci"
#  LOCATION: "southeastasia"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Client Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/multi-client ./client
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/multi-client:latest

      - name: Build and Push Nginx Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/multi-nginx ./nginx
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/multi-nginx:latest

      - name: Build and Push Server Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/multi-server ./server
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/multi-server:latest

      - name: Build and Push Worker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/multi-worker ./worker
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/multi-worker:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Multi-Container to ACI
        uses: azure/azure-cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az container create \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --file ./aci-compose.yaml
